# Generated by Django 3.0.5 on 2021-03-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('narrator', models.CharField(max_length=100, verbose_name='Narrator')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded')),
            ],
            options={
                'verbose_name': 'AudioBook',
                'verbose_name_plural': 'AudioBooks',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded')),
                ('host', models.CharField(max_length=100, verbose_name='Host')),
                ('participants', models.CharField(max_length=1009, verbose_name='Participants')),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcasts',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
